### ISSUE TITLE
Testing what an Issue behaves like in a project context.

### ISSUE THREAD

**Issue by taoteg** [TACC/Core-CMS#102]
Test issue, not for real.

**Comment by taoteg** [comment]
Looks like we can chat about details here....

**Comment by tacc-wbomar** [comment]
Ah, this is for [the TACC Organization Project "Core"](https://github.com/orgs/TACC/projects/2#card-53859967).

I have considered moving some of the [Core CMS projects](https://github.com/TACC/Core-CMS/projects) to the TACC organization, but [there is not a way to migrate a whole project from a repository to an organization](https://github.community/t/move-a-github-project-from-a-repository-to-organization/142336/2).

Whether I should do this should be answered now, before I add even more issues (which I will do), so that I have less issues to move one by one.

@jgentle, thoughts?
